import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import usersRouter from "./users";
import postsRouter from "./posts";
import commentsRouter from "./comments";
import messagesRouter from "./messages";
import confessionsRouter from "./confessions";
import circlesRouter from "./circles";
import creatorRouter from "./creator";
import notificationsRouter from "./notifications";
import contestsRouter from "./contests";
import openaiRouter from "./openai";
import boostsRouter from "./boosts";
import stripeRouter from "./stripe";
import purgeRouter from "./purge";
import dreamsRouter from "./dreams";
import albumsRouter from "./albums";
import badgesRouter from "./badges";
import appstoreRouter from "./appstore";
import visitorsRouter from "./visitors";
import vitalsRouter from "./vitals";
import purgatoryRouter from "./purgatory";
import shadowWorkRouter from "./shadow-work";
import ttsRouter from "./tts";
import betsRouter from "./bets";
import podcastRouter from "./podcast";
import liveRouter from "./live";
import frequencyMatchRouter from "./frequency-match";
import masqueradeRouter from "./masquerade";
import pranksRouter from "./pranks";
import pushRouter from "./push";
import referralsRouter from "./referrals";
import accountRouter from "./account";
import membershipRouter from "./membership";
import callsRouter from "./calls";
import papsRouter from "./paps";
import voteRouter from "./vote";
import presenceRouter from "./presence";
import entitlementsRouter from "./entitlements";
import botsRouter from "./bots";
import ghostLettersRouter from "./ghost-letters";
import mirrorMomentRouter from "./mirror-moment";
import patternsRouter from "./patterns";
import witnessWallRouter from "./witness-wall";
import penPalsRouter from "./pen-pals";
import shadowWorkSharedRouter from "./shadow-work-shared";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(postsRouter);
router.use(commentsRouter);
router.use(messagesRouter);
router.use(confessionsRouter);
router.use(circlesRouter);
router.use(creatorRouter);
router.use(notificationsRouter);
router.use(contestsRouter);
router.use(openaiRouter);
router.use(boostsRouter);
router.use(stripeRouter);
router.use(purgeRouter);
router.use(dreamsRouter);
router.use(albumsRouter);
router.use(badgesRouter);
router.use(appstoreRouter);
router.use(visitorsRouter);
router.use(vitalsRouter);
router.use(purgatoryRouter);
router.use(shadowWorkRouter);
router.use(ttsRouter);
router.use(betsRouter);
router.use(podcastRouter);
router.use(liveRouter);
router.use(frequencyMatchRouter);
router.use(masqueradeRouter);
router.use(pranksRouter);
router.use(pushRouter);
router.use(referralsRouter);
router.use(accountRouter);
router.use(membershipRouter);
router.use(callsRouter);
router.use(papsRouter);
router.use(voteRouter);
router.use(presenceRouter);
router.use(entitlementsRouter);
router.use(botsRouter);
router.use(ghostLettersRouter);
router.use(mirrorMomentRouter);
router.use(patternsRouter);
router.use(witnessWallRouter);
router.use(penPalsRouter);
router.use(shadowWorkSharedRouter);
router.use(adminRouter);

export default router;
