export const ZODIAC_SIGNS = [
  { sign: "Aries", symbol: "♈", dates: "Mar 21 – Apr 19", element: "Fire", traits: ["Bold", "Impulsive", "Courageous", "Competitive"] },
  { sign: "Taurus", symbol: "♉", dates: "Apr 20 – May 20", element: "Earth", traits: ["Reliable", "Stubborn", "Sensual", "Patient"] },
  { sign: "Gemini", symbol: "♊", dates: "May 21 – Jun 20", element: "Air", traits: ["Curious", "Adaptable", "Witty", "Indecisive"] },
  { sign: "Cancer", symbol: "♋", dates: "Jun 21 – Jul 22", element: "Water", traits: ["Nurturing", "Intuitive", "Moody", "Protective"] },
  { sign: "Leo", symbol: "♌", dates: "Jul 23 – Aug 22", element: "Fire", traits: ["Confident", "Generous", "Dramatic", "Loyal"] },
  { sign: "Virgo", symbol: "♍", dates: "Aug 23 – Sep 22", element: "Earth", traits: ["Analytical", "Perfectionist", "Practical", "Helpful"] },
  { sign: "Libra", symbol: "♎", dates: "Sep 23 – Oct 22", element: "Air", traits: ["Diplomatic", "Charming", "Indecisive", "Social"] },
  { sign: "Scorpio", symbol: "♏", dates: "Oct 23 – Nov 21", element: "Water", traits: ["Intense", "Secretive", "Loyal", "Magnetic"] },
  { sign: "Sagittarius", symbol: "♐", dates: "Nov 22 – Dec 21", element: "Fire", traits: ["Adventurous", "Honest", "Restless", "Philosophical"] },
  { sign: "Capricorn", symbol: "♑", dates: "Dec 22 – Jan 19", element: "Earth", traits: ["Ambitious", "Disciplined", "Cautious", "Resourceful"] },
  { sign: "Aquarius", symbol: "♒", dates: "Jan 20 – Feb 18", element: "Air", traits: ["Visionary", "Independent", "Eccentric", "Humanitarian"] },
  { sign: "Pisces", symbol: "♓", dates: "Feb 19 – Mar 20", element: "Water", traits: ["Empathetic", "Dreamy", "Intuitive", "Escapist"] },
];

export const ELEMENT_COLORS: Record<string, string> = {
  Fire: "text-orange-400 border-orange-400/40 bg-orange-400/10",
  Earth: "text-green-400 border-green-400/40 bg-green-400/10",
  Air: "text-sky-400 border-sky-400/40 bg-sky-400/10",
  Water: "text-blue-400 border-blue-400/40 bg-blue-400/10",
};

export const MBTI_TYPES = [
  {
    type: "INTJ",
    nickname: "The Architect",
    group: "Analyst",
    color: "text-violet-400 border-violet-400/40 bg-violet-400/10",
    traits: ["Strategic", "Independent", "Decisive", "Private"],
    description: "Rare and brilliant minds who see patterns in everything.",
  },
  {
    type: "INTP",
    nickname: "The Thinker",
    group: "Analyst",
    color: "text-violet-400 border-violet-400/40 bg-violet-400/10",
    traits: ["Logical", "Inventive", "Detached", "Flexible"],
    description: "Logic-driven explorers who question everything.",
  },
  {
    type: "ENTJ",
    nickname: "The Commander",
    group: "Analyst",
    color: "text-violet-400 border-violet-400/40 bg-violet-400/10",
    traits: ["Bold", "Strategic", "Efficient", "Charismatic"],
    description: "Natural-born leaders who thrive on challenge.",
  },
  {
    type: "ENTP",
    nickname: "The Debater",
    group: "Analyst",
    color: "text-violet-400 border-violet-400/40 bg-violet-400/10",
    traits: ["Innovative", "Argumentative", "Energetic", "Sharp"],
    description: "Devil's advocates who love a good mental sparring match.",
  },
  {
    type: "INFJ",
    nickname: "The Advocate",
    group: "Diplomat",
    color: "text-green-400 border-green-400/40 bg-green-400/10",
    traits: ["Empathetic", "Visionary", "Private", "Principled"],
    description: "The rarest type — deeply idealistic, quietly powerful.",
  },
  {
    type: "INFP",
    nickname: "The Mediator",
    group: "Diplomat",
    color: "text-green-400 border-green-400/40 bg-green-400/10",
    traits: ["Idealistic", "Creative", "Sensitive", "Loyal"],
    description: "Poetic souls searching for meaning in everything.",
  },
  {
    type: "ENFJ",
    nickname: "The Protagonist",
    group: "Diplomat",
    color: "text-green-400 border-green-400/40 bg-green-400/10",
    traits: ["Charismatic", "Inspiring", "Persuasive", "Empathetic"],
    description: "Natural teachers who rally people toward their potential.",
  },
  {
    type: "ENFP",
    nickname: "The Campaigner",
    group: "Diplomat",
    color: "text-green-400 border-green-400/40 bg-green-400/10",
    traits: ["Enthusiastic", "Creative", "Sociable", "Free-spirited"],
    description: "Boundless energy, big ideas, and infectious optimism.",
  },
  {
    type: "ISTJ",
    nickname: "The Logistician",
    group: "Sentinel",
    color: "text-blue-400 border-blue-400/40 bg-blue-400/10",
    traits: ["Reliable", "Organized", "Traditional", "Responsible"],
    description: "The backbone of institutions — steady, thorough, trustworthy.",
  },
  {
    type: "ISFJ",
    nickname: "The Defender",
    group: "Sentinel",
    color: "text-blue-400 border-blue-400/40 bg-blue-400/10",
    traits: ["Caring", "Loyal", "Observant", "Modest"],
    description: "Devoted protectors who carry the world on quiet shoulders.",
  },
  {
    type: "ESTJ",
    nickname: "The Executive",
    group: "Sentinel",
    color: "text-blue-400 border-blue-400/40 bg-blue-400/10",
    traits: ["Organized", "Assertive", "Practical", "Direct"],
    description: "Natural managers who uphold order and tradition.",
  },
  {
    type: "ESFJ",
    nickname: "The Consul",
    group: "Sentinel",
    color: "text-blue-400 border-blue-400/40 bg-blue-400/10",
    traits: ["Warm", "Social", "Loyal", "Caring"],
    description: "Community pillars who make everyone feel welcome.",
  },
  {
    type: "ISTP",
    nickname: "The Virtuoso",
    group: "Explorer",
    color: "text-amber-400 border-amber-400/40 bg-amber-400/10",
    traits: ["Bold", "Practical", "Observant", "Self-reliant"],
    description: "Master craftspeople who learn by doing.",
  },
  {
    type: "ISFP",
    nickname: "The Adventurer",
    group: "Explorer",
    color: "text-amber-400 border-amber-400/40 bg-amber-400/10",
    traits: ["Artistic", "Curious", "Gentle", "Spontaneous"],
    description: "Quiet rebels who live fully in the present moment.",
  },
  {
    type: "ESTP",
    nickname: "The Entrepreneur",
    group: "Explorer",
    color: "text-amber-400 border-amber-400/40 bg-amber-400/10",
    traits: ["Bold", "Perceptive", "Direct", "Sociable"],
    description: "Live wires who thrive on action and risk.",
  },
  {
    type: "ESFP",
    nickname: "The Entertainer",
    group: "Explorer",
    color: "text-amber-400 border-amber-400/40 bg-amber-400/10",
    traits: ["Spontaneous", "Energetic", "Playful", "Bold"],
    description: "Life of every party — warm, fun, and wonderfully real.",
  },
];

export const PET_TYPES = [
  { key: "petCats", label: "Cats", icon: "🐱" },
  { key: "petDogs", label: "Dogs", icon: "🐶" },
  { key: "petBirds", label: "Birds", icon: "🐦" },
  { key: "petFish", label: "Fish", icon: "🐠" },
  { key: "petRabbits", label: "Rabbits", icon: "🐰" },
  { key: "petHamsters", label: "Hamsters", icon: "🐹" },
  { key: "petReptiles", label: "Reptiles", icon: "🦎" },
];
